export const endpoints = {
  refreshToken: "/user/superadmin/refresh-token",
  getData: "/getData",
  login: "/user/login",
  logout: "/user/logout",
  changePassword: "/user/change-password",
  resetPassword: "/user/reset-password",
  forgotPassword: "/user/forgot-password",
  createUser: "/user/register",
  getUser: "/user/list/search/",
  getProfile: "/user/profile",
  updateuserById: "/user/update-profile/",
  deleteUserById: "/user/delete/",
  module: "/manpower/module/by-tenant",
  userVerify: "/user/me",
  locations: "/location",
  dashboard: {
    totalStatistics: {
      list: "/manpower/dashboard/total-stats",
    },
    activities: {
      list: "/manpower/recent-activity",
    },
  },
  organizationSettings: {
    list: "/organization-settings/list",
    create: "/organization-settings/create",
    update: "/organization-settings/update",
    delete: "/organization-settings/delete",
    details: "/organization/detail/id/",
  },
  preApprovalDofe: {
    list: "/manpower/predofeapproval",
    create: "/manpower/predofeapproval",
    update: "/manpower/predofeapproval/:id",
    delete: "/manpower/predofeapproval/:id",
    details: "/manpower/predofeapproval/:id",
  },
  candidates: {
    personalDetails: {
      create: "/admin/jobseeker",
      list: "/admin/jobseeker",
      update: "/admin/jobseeker/:id",
      delete: "/admin/jobseeker/:id",
      details: "/admin/jobseeker/:id",
    },
    skillandLanguages: {
      create: "/admin/jobseeker/skill-language/:id",
      list: "/admin/jobseeker/skill-language",
      update: "/admin/jobseeker/skill-language/:id",
      delete: "/admin/jobseeker/skill-language/:id",
      details: "/admin/jobseeker/skill-language/:id",
    },
    education: {
      create: "/admin/jobseeker/education",
      list: "/admin/jobseeker/:id/education",
      update: "/admin/jobseeker/:jobSeekerId/education/:id",
      delete: "/admin/jobseeker//:jobSeekerId/education/:id",
      details: "/admin/jobseeker/:jobSeekerId/education/:id",
    },
    experience: {
      create: "/admin/jobseeker/experience",
      list: "/admin/jobseeker/:id/experience",
      update: "/admin/jobseeker/:jobSeekerId/experience/:id",
      delete: "/admin/jobseeker/:jobSeekerId/experience/:id",
      details: "/admin/jobseeker/:jobSeekerId/experience/:id",
    },
    certificate: {
      create: "/admin/jobseeker/certificate",
      list: "/admin/jobseeker/:id/certificate",
      update: "/admin/jobseeker/:jobSeekerId/certificate/:id",
      delete: "/admin/jobseeker/:jobSeekerId/certificate/:id",
      details: "/admin/jobseeker/:jobSeekerId/certificate/:id",
    },
    personalDocument: {
      create: "/admin/jobseeker/personal-document",
      list: "/admin/jobseeker/:id/personal-document",
      update: "/admin/jobseeker/personal-document/",
      delete: "/admin/jobseeker/:jobSeekerId/personal-document/",
      details: "/admin/jobseeker/:jobSeekerId/personal-document/",
    },
    appliedJob: {
      create: "/admin/jobseeker/applied-job",
      list: "/admin/jobseeker/:id/applied-job",
      update: "/admin/jobseeker/:jobSeekerId/applied-job/:id",
      delete: "/admin/jobseeker/:jobSeekerId/applied-job/:id",
      details: "/admin/jobseeker/:jobSeekerId/applied-job/:id",
    },
    interviewStatus: "/admin/jobseeker",
  },
  jobVacancy: {
    list: "/manpower/predofeapproval/jobvacancy",
  },
  country: {
    list: "/manpower/country",
    create: "/manpower/country",
    update: "/manpower/country/:id",
    delete: "/manpower/country/:id",
    details: "/manpower/country/:id",
  },
  interviewSchedule: {
    list: "/manpower/job-interview",
    create: "/manpower/job-interview",
    update: "/manpower/job-interview/:id",
    delete: "/manpower/job-interview/:id",
    details: "/manpower/job-interview/:id",
  },
  jobOffer: {
    list: "/manpower/job-offer",
    create: "/manpower/job-offer",
    update: "/manpower/job-offer/:id",
    delete: "/manpower/job-offer/:id",
    details: "/manpower/job-offer/:id",
  },
  medical: {
    list: "/manpower/medical-report",
    create: "/manpower/medical-report",
    update: "/manpower/medical-report/:id",
    delete: "/manpower/medical-report/:id",
    details: "/manpower/medical-report/:id",
  },
  visa: {
    list: "/manpower/visa",
    create: "/manpower/visa",
    update: "/manpower/visa/:id",
    delete: "/manpower/visa/:id",
    details: "/manpower/visa/:id",
  },
  orientation: {
    list: "/manpower/orientation",
    create: "/manpower/orientation",
    update: "/manpower/orientation/:id",
    delete: "/manpower/orientation/:id",
    details: "/manpower/orientation/:id",
  },
  insurance: {
    list: "/manpower/insurance",
    create: "/manpower/insurance",
    update: "/manpower/insurance/:id",
    delete: "/manpower/insurance/:id",
    details: "/manpower/insurance/:id",
  },
  invoice: {
    list: "/manpower/invoice",
    create: "/manpower/invoice",
    update: "/manpower/invoice/:id",
    delete: "/manpower/invoice/:id",
    details: "/manpower/invoice/:id",
  },
  expense: {
    list: "/manpower/expense",
    create: "/manpower/expense",
    update: "/manpower/expense/:id",
    delete: "/manpower/expense/:id",
    details: "/manpower/expense/:id",
  },
  quickPayment: {
    list: "/manpower/quick-payment",
    create: "/manpower/quick-payment",
    update: "/manpower/quick-payment/:id",
    delete: "/manpower/quick-payment/:id",
    details: "/manpower/quick-payment/:id",
  },
  shram: {
    list: "/manpower/shram",
    create: "/manpower/shram",
    update: "/manpower/shram/:id",
    delete: "/manpower/shram/:id",
    details: "/manpower/shram/:id",
  },
  ticket: {
    list: "/manpower/ticket",
    create: "/manpower/ticket",
    update: "/manpower/ticket/:id",
    delete: "/manpower/ticket/:id",
    details: "/manpower/ticket/:id",
  },
  bank: {
    list: "/manpower/bank-setting",
    create: "/manpower/bank-setting",
    update: "/manpower/bank-setting/:id",
    delete: "/manpower/bank-setting/:id",
    details: "/manpower/bank-setting/:id",
  },
  document: {
    list: "/manpower/document-setting",
    create: "/manpower/document-setting",
    update: "/manpower/document-setting/:id",
    delete: "/manpower/document-setting/:id",
    details: "/manpower/document-setting/:id",
  },
  company: {
    list: "/manpower/company-recruitment",
    create: "/manpower/company-recruitment",
    update: "/manpower/company-recruitment/:id",
    delete: "/manpower/company-recruitment/:id",
    details: "/manpower/company-recruitment/:id",
  },
  chartOfAccount: {
    account: {
      list: "/manpower/account",
      create: "/manpower/account",
      update: "/manpower/account/:id",
      delete: "/manpower/account/:id",
      details: "/manpower/account/:id",
    },
    group: {
      list: "/manpower/group",
      create: "/manpower/group",
      update: "/manpower/group/:id",
      delete: "/manpower/group/:id",
      details: "/manpower/group/:id",
    },
  },
  chequeIssued: {
    list: "/manpower/cheque-issued",
    create: "/manpower/cheque-issued",
    update: "/manpower/cheque-issued/:id",
    delete: "/manpower/cheque-issued/:id",
    details: "/manpower/cheque-issued/:id",
  },
  chequeReceived: {
    list: "/manpower/cheque-received",
    create: "/manpower/cheque-received",
    update: "/manpower/cheque-received/:id",
    delete: "/manpower/cheque-received/:id",
    details: "/manpower/cheque-received/:id",
  },
  supplier: {
    list: "/manpower/supplier",
    create: "/manpower/supplier",
    update: "/manpower/supplier/:id",
    delete: "/manpower/supplier/:id",
    details: "/manpower/supplier/:id",
  },
  membership: {
    list: "/manpower/membership",
    create: "/manpower/membership",
    update: "/manpower/membership",
  },
  user: {
    list: "/user",
    create: "/user/tenant",
    update: "/user/:id",
    delete: "/user/:id",
    details: "/user/:id",
  },
  role: {
    list: "/manpower/role",
    create: "/manpower/role",
    update: "/manpower/role/:id",
    delete: "/manpower/role/:id",
    details: "/manpower/role/:id",
  },
  permission: {
    list: "/manpower/permission",
    create: "/manpower/permission",
    update: "/manpower/permission/:id",
    delete: "/manpower/permission/:id",
    details: "/manpower/permission/:id",
  },
  insuranceCompany: {
    list: "/manpower/insurance-company",
    create: "/manpower/insurance-company",
    update: "/manpower/insurance-company/:id",
    delete: "/manpower/insurance-company/:id",
    details: "/manpower/insurance-company/:id",
  },
  medicalInstitute: {
    list: "/manpower/medical-institute",
    create: "/manpower/medical-institute",
    update: "/manpower/medical-institute/:id",
    delete: "/manpower/medical-institute/:id",
    details: "/manpower/medical-institute/:id",
  },
  orientationInstitute: {
    list: "/manpower/orientation-institute",
    create: "/manpower/orientation-institute",
    update: "/manpower/orientation-institute/:id",
    delete: "/manpower/orientation-institute/:id",
    details: "/manpower/orientation-institute/:id",
  },
  jobsetting: {
    category: {
      list: "/manpower/category",
      create: "/manpower/category",
      update: "/manpower/category/:id",
      delete: "/manpower/category/:id",
      details: "/manpower/category/:id",
    },
    industry: {
      list: "/manpower/industry",
      create: "/manpower/industry",
      update: "/manpower/industry/:id",
      delete: "/manpower/industry/:id",
      details: "/manpower/industry/:id",
    },
    subCategory: {
      list: "/manpower/subcategory",
      create: "/manpower/subcategory",
      update: "/manpower/subcategory/:id",
      delete: "/manpower/subcategory/:id",
      details: "/manpower/subcategory/:id",
    },
    jobTitle: {
      list: "/manpower/jobtitle",
      create: "/manpower/jobtitle",
      update: "/manpower/jobtitle/:id",
      delete: "/manpower/jobtitle/:id",
      details: "/manpower/jobtitle/:id",
    },
  },
};

export const BASE_API_URL =
  import.meta.env.VITE_PUBLIC_API_URL || "https://api.manpower.com";
